

export const IMAGES = {
    LOGO: require('./logo.png'),
    ANDROID_ICON_BG: require('./android-icon-background.png'),
    ANDROID_ICON_FG: require('./android-icon-foreground.png'),
    ANDROID_ICON_MONOCHROME: require('./android-icon-monochrome.png'),
    ANDROID_FAVICON: require('./favicon.png'),
    ANDROID_ICON: require('./icon.png'),
    PATIENT_PLACEHOLDER: require('./placeholders/patient-placeholder.png'),
    EYES_ZONE: require('./zones/eyes.png'),
    FOREHEAD_ZONE: require('./zones/forehead.png'),
    GLABELLA_ZONE: require('./zones/glabella.png'),
    HYPERHIDROSIS_ZONE: require('./zones/hyperhidrosis.png'),
    LIPS_ZONE: require('./zones/lips.png'),
    MASSETER_ZONE: require('./zones/masseter.png'),
    NECK_ZONE: require('./zones/neck.png'),
    NOSE_ZONE: require('./zones/nose.png'),
    OVAL_ZONE: require('./zones/oval.png'),
    TEMPORAL_ZONE: require('./zones/temporal.png'),
    SYRINGE: require('./syringe.png'),
    USER_IMG: require('./user-img.png'),
    BRONZE: require('./bronze.png'),
    SILVER: require('./silver.png'),
    GOLD: require('./gold.png'),
    BANK_CARDS: require('./bank-cards-icons.png'),
    SBP_ICON: require('./sbp.png'),
    YOMONEY_ICON: require('./yomoney.png'),
}
