export enum AppointmentCreateStepsEnum {
  PATIENT_FORM = 'PATIENT_FORM',
  PROCEDURE = 'PROCEDURE',
  INJECTION_ZONES = 'INJECTION_ZONES',
  PHOTO = 'PHOTO',
  INJECTION_INTENSITY = 'INJECTION_INTENSITY',
  PREPARATION_DISTRIBUTION = 'PREPARATION_DISTRIBUTION',
  SINGLE_SYRINGE = 'SINGLE_SYRINGE',
  MULTIPLE_SYRINGES = 'MULTIPLE_SYRINGES',
  ZONE_SETUP = 'ZONE_SETUP',
  APPOINTMENT_COMPLETION = 'APPOINTMENT_COMPLETION',
}
