export enum InspectionCreateStepsEnum {
  INJECTION_ZONES_1 = 'INJECTION_ZONES_1',
  CAMERA_PHOTO = 'CAMERA_PHOTO',
  BEFORE_AFTER_COLLAGE = 'BEFORE_AFTER_COLLAGE',
  MARK_POINTS = 'MARK_POINTS',
  INJECTION_ZONES_2 = 'INJECTION_ZONES_2',
  APPOINTMENT_COMPLETION = 'APPOINTMENT_COMPLETION',
}
