import type { IPatient } from '../interfaces';

export const patientsFaker: IPatient[] = [
  {
    id: '1',
    firstName: 'Анна',
    lastName: 'Петрова',
    middleName: 'Сергеевна',
    gender: 'female',
    birthDate: new Date(1985, 2, 15),
    phone: '+7 (999) 123-45-67',
    refuseReminders: false,
    imageUrl: 'https://i.pravatar.cc/150?img=1',
    createdAt: new Date(2023, 5, 10),
    updatedAt: new Date(2024, 10, 20),
  },
  {
    id: '2',
    firstName: 'Дмитрий',
    lastName: 'Козлов',
    middleName: 'Александрович',
    gender: 'male',
    birthDate: new Date(1978, 7, 22),
    phone: '+7 (912) 345-67-89',
    refuseReminders: false,
    imageUrl: 'https://i.pravatar.cc/150?img=3',
    createdAt: new Date(2022, 1, 5),
    updatedAt: new Date(2024, 9, 15),
  },
  {
    id: '3',
    firstName: 'Елена',
    lastName: 'Смирнова',
    middleName: 'Ивановна',
    gender: 'female',
    birthDate: new Date(1990, 11, 8),
    phone: '+7 (905) 678-90-12',
    refuseReminders: true,
    imageUrl: 'https://i.pravatar.cc/150?img=5',
    createdAt: new Date(2024, 0, 12),
    updatedAt: new Date(2024, 11, 1),
  },
  {
    id: '4',
    firstName: 'Михаил',
    lastName: 'Новиков',
    middleName: undefined,
    gender: 'male',
    birthDate: undefined,
    phone: '+7 (926) 111-22-33',
    refuseReminders: false,
    imageUrl: undefined,
    createdAt: new Date(2024, 6, 20),
    updatedAt: new Date(2024, 6, 20),
  },
  {
    id: '5',
    firstName: 'Ольга',
    lastName: 'Морозова',
    middleName: 'Викторовна',
    gender: 'female',
    birthDate: new Date(1982, 4, 30),
    phone: '+7 (916) 444-55-66',
    refuseReminders: false,
    imageUrl: 'https://i.pravatar.cc/150?img=9',
    specialFeatures: 'Аллергия на лидокаин',
    reminderInterval: '7',
    createdAt: new Date(2021, 8, 1),
    updatedAt: new Date(2023, 2, 15),
  },
  {
    id: '6',
    firstName: 'Сергей',
    lastName: 'Волков',
    middleName: 'Петрович',
    gender: 'male',
    birthDate: new Date(1975, 0, 12),
    phone: '+7 (903) 777-88-99',
    refuseReminders: false,
    imageUrl: undefined,
    createdAt: new Date(2024, 3, 8),
    updatedAt: new Date(2024, 11, 28),
  },
  {
    id: '7',
    firstName: 'Татьяна',
    lastName: 'Кузнецова',
    middleName: 'Николаевна',
    gender: 'female',
    birthDate: new Date(1988, 9, 25),
    phone: '+7 (921) 555-12-34',
    refuseReminders: false,
    imageUrl: 'https://i.pravatar.cc/150?img=20',
    createdAt: new Date(2023, 11, 1),
    updatedAt: new Date(2024, 10, 10),
  },
  {
    id: '8',
    firstName: 'Алексей',
    lastName: 'Соколов',
    middleName: 'Дмитриевич',
    gender: 'male',
    birthDate: new Date(1992, 6, 3),
    phone: '+7 (495) 123-45-67',
    refuseReminders: false,
    imageUrl: 'https://i.pravatar.cc/150?img=12',
    createdAt: new Date(2024, 2, 15),
    updatedAt: new Date(2024, 11, 5),
  },
];
